#!/usr/bin/env bash

if [ ! "$1" ]; then
    echo 'Usage: BMT=<times to run> time bashmark "<command>"' >&2
    return 1
fi

ts="${BMT:-1000}"

for num in $(seq -- "$ts"); do
    printf '%d\n%d\n%d\n' "$num" "$num$num" "$num$num$num" | bash -c -- "$1"
done
