#!/usr/bin/env sh

set -e

main() {
    if [ ! "$1" ]; then
        echo 'Usage: BMT=<times to run> time bashmark "<command>"' >&2
        return 1
    fi

    for num in $(seq -- "${BMT:-1000}"); do
        printf '%d\n%d\n%d\n' "$num" "$num$num" "$num$num$num" | bash -c -- "$1"
    done
}

main "$@"
